### ISSUE TITLE
jmp far ptr and zeroExtend()

### ISSUE THREAD

**Issue by nastypuma** [cea-sec/miasm#709] opened 2018-03-29 16:51 UTC
Hi ! I'm still working on reversing a 16bits bootloader. I emulate BIOS interrupts but now I'm encoutering an error during the jump to the second stage. 

It seems that I have a problem with the decoding/processing of jmp far ptr, because one assert in zeroExtend() function failes. Once again, I may be completely wrong because I'm new and I don't have knowledge on miasm internals.

I made a gist with the differents code snippets, output and the traceback here : https://gist.github.com/nastypuma/07e34394798b35f63fa86504f258c467

**Comment by serpilliere** [comment] 2018-03-30 11:43
Hi!

Can you give me the raw bytes of the mbr (I mean at last until the jmp far)?
If no, at last the raw bytes of the jmp far.
I will try to reproduce the bug here

Thanks!

**Comment by nastypuma** [comment] 2018-03-31 15:44
Is an hexdump ok for you ?
https://gist.github.com/nastypuma/c006dd68159f6d8b0e13ba81c04ca8de

Also, I can send you the binary if you prefer.

Thanks !

**Comment by serpilliere** [comment] 2018-04-01 17:39
Ok. Got it.
The problem is that Miasm considers the program counter in 16bit is 16bit long.
Executing a `jump far` will affect the `CS`, but also the program counter, in this case with a 32 bit value as the prefix 66 is used (usefull for example to leave the 16bit world to 32 bit world with good segments selectors).

Miasm breaks during the semantic generation. This is a first problem.
But that's not all: Even if we resolve this problem, we will face another one rapidly: During the jit, (or even during the disasm of next bytes), we will have to change the "attribute" of the architecture (16 bit to 32 bit disassemble), which is not supporte!d yet in any module of Miasm.

By the way, we have the very same problem in arm during the transition between arm and thumb (for the disassembler, for the jitter, ...)

Sadly, I don't have a ready solution for now :confused:

**Comment by commial** [comment] 2018-04-01 20:11
If the switch is only done once, you can break on it then change the `jitter.jit` instance by a 32 bits one. The `.vm` being the same, the memory state will be consistent. You just have to copy the registers values (and segments) from one instance to the other to have the register state consistent.

Well, this is a manual step, but it may help if you want to continue the emulation

**Comment by nastypuma** [comment] 2018-04-02 08:57
This type of jump appears only one time in the code.
So I think I will try your solution @commial 
I'll tell you the result so we can close the issue if it's fine :)

**Comment by nastypuma** [comment] 2018-04-20 13:52
The assembly code where the jmp far must go is also in 16 bits.
So no need to switch from 16 to 32 vm. I juste wrote a dirty breakpoint on the jmp far ptr and set PC to the right location.
Problem solved, issue can be closed.
Sorry for the delay of the answer.
Thanks !

**Comment by serpilliere** [comment] 2018-04-20 15:34
I am closing it but we are keeping this in mind for the global design error.
Thanks!

**Closed by serpilliere** 2018-04-20 15:34 UTC
