### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Solver'

### ISSUE THREAD

**Issue by gitttt** [cea-sec/miasm#370] opened 2016-05-27 13:04 UTC
I loaded the depgraph.py from within IDA Pro, chose a register and selected 

- "At the end of the basic block"
- A register to track
- "Implicit dependencies"

The last option seems to cause the following error:
```
/home/vagrant/miasm/example/ida/depgraph.py: 'module' object has no attribute 'Solver'
Traceback (most recent call last):
  File "/opt/ida-6.9/python/idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "/home/vagrant/miasm/example/ida/depgraph.py", line 240, in <module>
    treat_element()
  File "/home/vagrant/miasm/example/ida/depgraph.py", line 228, in treat_element
    print "Possible value: %s" % graph.emul().values()[0]
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/depgraph.py", line 359, in emul
    solver = z3.Solver()
AttributeError: 'module' object has no attribute 'Solver'
```
Note that I installed
`sudo pip install z3`

**Comment by serpilliere** [comment] 2016-05-27 13:16
If you have installed IDA using bundled python, you have to install z3 in this python! (IDA_DIR/python)

**Comment by gitttt** [comment] 2016-05-27 13:24
From the IDA Python command line window:
`Python>sys.executable`
`/usr/bin/python`

Also, from the IDA Python command line I can do:
`Python>import z3`
`Python>dir(z3)`
`['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']`

So I guess I am using the system python...

**Comment by serpilliere** [comment] 2016-05-27 14:24
In a python shell, can you execute:
```python
import z3
a = z3.Solver()
```
Can you do the same in the IDA python shell as well?

**Comment by gitttt** [comment] 2016-05-27 18:17
```
vagrant@packer-virtualbox-iso-1464112746:/tmp$ python
Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> a = z3.Solver()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Solver'
```

So this is a z3 issue. Did I install the "wrong" z3 python package? Pip says:
```
vagrant@packer-virtualbox-iso-1464112746:/tmp$ pip list
[...]
boto (2.28.0)
[...]
ElfEsteem (0.1)
[...]
Miasm (2.0)
[...]
pip (1.5.4)
[...]
xdot (0.5)
z3 (0.1.13)
zope.interface (4.0.5)
```

**Comment by gitttt** [comment] 2016-05-27 18:20
I have no z3 installed other than the pip-installed python z3. Maybe this is the problem?

**Comment by serpilliere** [comment] 2016-05-27 19:08
You have the `z3` version used in the regression tests in the travis file:
```
"mkdir z3 && cd z3 && wget -O z3.zip 'http://download-codeplex.sec.s-msft.com/Download/SourceControlFileDownload.ashx?ProjectName=z3&changeSetId=cee7dd39444c9060186df79c2a2c7f8845de415b'"
```

This is different from the z3 in PIP modules (some sites explain the pip module version is broken ?!?)

**Comment by gitttt** [comment] 2016-05-27 19:11
Yeah, thanks for the hint. It is not really a miasm related problem. Sorry I bothered you. I will leave a note here once it works anyway.

**Comment by serpilliere** [comment] 2016-05-27 19:18
Are you ok if I close the issue? (you will be able to add your comment anyway)

**Comment by gitttt** [comment] 2016-05-27 19:18
Sure sure.

**Closed** 2016-05-27 19:21 UTC

**Comment by gitttt** [comment] 2016-05-27 20:17
The error went away once I have installed the z3 you linked above. The z3 from the official github worked as well. Yet, with either of the two z3-installations, I got a new error:

```
/home/vagrant/miasm/example/ida/depgraph.py: Unsupported OP yet: call_func_ret
Traceback (most recent call last):
  File "/opt/ida-6.9/python/idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "/home/vagrant/miasm/example/ida/depgraph.py", line 240, in <module>
    treat_element()
  File "/home/vagrant/miasm/example/ida/depgraph.py", line 228, in treat_element
    print "Possible value: %s" % graph.emul().values()[0]
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/depgraph.py", line 378, in emul
    self._gen_path_constraints(translator, dst, expected))
  File "/usr/local/lib/python2.7/dist-packages/miasm2/analysis/depgraph.py", line 338, in _gen_path_constraints
    for cond in consval.constraints])
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/translators/translator.py", line 113, in from_expr
    ret = handler(expr)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/ir/translators/z3_ir.py", line 209, in from_ExprAff
    dst = self.from_expr(expr.dst)
  File "/usr/local/lib/python2.7/dist-packag
```
Is this a bug, an indicator for a mistake by me, or just something "Unsupported yet" ?

**Comment by commial** [comment] 2016-05-27 21:34
This is because you have a constraint on the output of a function. The operator `call_func_ret` is here to simulate a relation between the output of a function and its argument, without going deep into in.

In this case, it is not possible to (or, at least, without going into the callee) to obtain a value for the desired element.
But, we may have to transform this crash intro a warning :smile: 
So, thanks for reporting it!

If you still want a result, you can replace this expression (`call_func_ret`) with an `ExprId` standing for the returned value of the function, like `ExprId('myfunc_ret1')`.

**Comment by serpilliere** [comment] 2016-05-27 23:21
I agree with you. But the user has to either simulate the sub call or doing the `ExprId` trick. So for me this last behavior is not a bug.

This should not be a warning as you cannot do any reasoning if you don't do one or other solution.

**Comment by xarkes** [comment] 2019-06-26 08:26
In case anybody stumbles on the same issue, the PIP package for z3 is called `z3-solver` not `z3`.
`pip install --user z3-solver`

**Comment by serpilliere** [comment] 2019-06-26 18:39
Thank you for the tips @xarkes!
