### ISSUE TITLE
Simplification ollvm -mllvm -sub

### ISSUE THREAD

**Issue by chago** [cea-sec/miasm#878] opened 2018-11-02 02:38 UTC
Dear gods，how to simplification ircfg's block?I want to Show change in the ircfg。
```
SUB             W12, W12, W8
ADD             W11, W12, W11
ADD             W8, W11, W8
```
transform to
```
ADD             W8, W11, W12
```

In ollvm :
```
r = rand (); a = b + r; a = a + c; a = a - r
%0 = load i32* %a, align 4
%1 = load i32* %b, align 4
%2 = add i32 %0, 1107414009
%3 = add i32 %2, %1
%4 = sub nsw i32 %3, 1107414009
```
When i symbolic execution each block,but my pass can't match it.
```
def simp_add_1(expr_simp, e):
    to_match = -jok1 + jok2 + jok3 + jok1

    result = MatchExpr(e, to_match, [jok1, jok2, jok3])

    if (result is False) or (result == {}):
        return e  # Doesn't match. Return unmodified expression
    return e

```

**Comment by serpilliere** [comment] 2018-11-03 13:16
As it seems there are no gods here, I will have a try answering the question.
First, your simplification may not be true:
```
SUB             W12, W12, W8
ADD             W11, W12, W11
ADD             W8, W11, W8
```
*cannot* simplify as:
```
ADD             W8, W11, W12
```
everywhere.

Imagine the next lines are using W11 or W12 for example! The simplification will be invalid.
Ok. Let's imagine we know that W11 and W12 are *dead* after the last ADD. the simplification is ok here.

So you have first to do this analyze. Miasm can help you here :smile: (using dead analyze)

That said, I will try to show you where the problem is in Miasm (and in most framework using intermediate language)

The framework (and many others) to not work on the native assembly but on the intermediate language. So you have a first pass which translate asm to IR.
Now, you can to all your pass analyzing the IR (I mean dead simplification, constant propagation, and other cools stuff).
This will result in a simplified *intermediate language representation*. Not in a simplified native assembly.

And here is the problem: it's hard to regenerate native assembly from this IR. I mean a *clean* assembly.

There is magic solution here.

Why?
For example, let's take a x86 instruction:
```
add eax, 3
```

The IR is something like:
```
zf = (EAX + 3 == 0) ? 1:0
nf = (EAX + 3) >> 31
...
EAX = EAX +3
```

Imagine you have done some simplifications which result in the fact that zf if not needed anymore. So you simplification pass deletes the IR line and results in:
```
nf = (EAX + 3) >> 31
...
EAX = EAX +3
```

Question now:
How can you *match* this IR to a native instruction:
```
add eax, 3
```
Why not generate a add and test eax of sf?
As the add will recreate the zf affectation anyway, is it ok to generate it anyway?


A trick which can be used is to use the fact that the IR from Miasm can generate IR for LLVM, so we can generate native (optimized :smiley: code) using it.
But It seems there is a problem remaining: we cannot "bind" our EAX in IR to the native EAX generated by llvm...
EAX is here considered as a variable, not the register EAX...

I hope it helps!

**Comment by commial** [comment] 2018-11-03 14:47
One thing which also could help, is that the generated IR keeps track of the asm line it comes from (AssignBlock.instr). If after IR simplification you notice that every AssignBlock related to one instr have been removed, you can consider removing the original assembly line. It could be useful after performing dead analysis pass. 
But in this specific case, as the expression to simplify comes from a symbolic execution, you'll lose provenance information. Even if it seems that the info is not really loose and can be recovered, in the general case it will not, due to information loss in simplifications.

**Comment by chago** [comment] 2018-11-05 02:38
> As it seems there are no gods here, I will have a try answering the question.
> First, your simplification may not be true:
> 
> ```
> SUB             W12, W12, W8
> ADD             W11, W12, W11
> ADD             W8, W11, W8
> ```
> _cannot_ simplify as:
> 
> ```
> ADD             W8, W11, W12
> ```
> everywhere.
> 
> Imagine the next lines are using W11 or W12 for example! The simplification will be invalid.
> Ok. Let's imagine we know that W11 and W12 are _dead_ after the last ADD. the simplification is ok here.
> 
> So you have first to do this analyze. Miasm can help you here 😄 (using dead analyze)
> 
> That said, I will try to show you where the problem is in Miasm (and in most framework using intermediate language)
> 
> The framework (and many others) to not work on the native assembly but on the intermediate language. So you have a first pass which translate asm to IR.
> Now, you can to all your pass analyzing the IR (I mean dead simplification, constant propagation, and other cools stuff).
> This will result in a simplified _intermediate language representation_. Not in a simplified native assembly.
> 
> And here is the problem: it's hard to regenerate native assembly from this IR. I mean a _clean_ assembly.
> 
> There is magic solution here.
> 
> Why?
> For example, let's take a x86 instruction:
> 
> ```
> add eax, 3
> ```
> The IR is something like:
> 
> ```
> zf = (EAX + 3 == 0) ? 1:0
> nf = (EAX + 3) >> 31
> ...
> EAX = EAX +3
> ```
> Imagine you have done some simplifications which result in the fact that zf if not needed anymore. So you simplification pass deletes the IR line and results in:
> 
> ```
> nf = (EAX + 3) >> 31
> ...
> EAX = EAX +3
> ```
> Question now:
> How can you _match_ this IR to a native instruction:
> 
> ```
> add eax, 3
> ```
> Why not generate a add and test eax of sf?
> As the add will recreate the zf affectation anyway, is it ok to generate it anyway?
> 
> A trick which can be used is to use the fact that the IR from Miasm can generate IR for LLVM, so we can generate native (optimized 😃 code) using it.
> But It seems there is a problem remaining: we cannot "bind" our EAX in IR to the native EAX generated by llvm...
> EAX is here considered as a variable, not the register EAX...
> 
> I hope it helps!

Thank you very much.
I want to use the optimized ir diagram to assist the analysis, it is best to remove the ollvm Bogus Control Flow, Control Flow Flattening and Instructions Substitution.
But after two days of viewing the fucking source code,I found that it can only optimize one instruction when run the graph_ir.py
```
 new_assignblk = {
                expr_simp(dst): expr_simp(src)
                for dst, src in assignblk.iteritems()
        }
```
Only the execution of symbols can remove the garbage such as Instructions Substitution,As the commial says,it will lose provenance information.So this idea is not achievable.

A trick which can be used is to use the fact that the IR from Miasm can generate IR for LLVM,this conversion has changed the prototype of the function, it can't be looked directly into the IDA,and the source code is split and converted in units of basic blocks.

**Comment by chago** [comment] 2018-11-05 02:46
> One thing which also could help, is that the generated IR keeps track of the asm line it comes from (AssignBlock.instr). If after IR simplification you notice that every AssignBlock related to one instr have been removed, you can consider removing the original assembly line. It could be useful after performing dead analysis pass.
> But in this specific case, as the expression to simplify comes from a symbolic execution, you'll lose provenance information. Even if it seems that the info is not really loose and can be recovered, in the general case it will not, due to information loss in simplifications.

Thank you very much！
I understand what you mean,if I want to remove the garbage, such as instructions substitution, I can only execute with symbols and lose provenance information。

**Closed** 2018-11-05 02:49 UTC
